// Game play
export const ADD_CARD_TO_GAME_TABLE = 'ADD_CARD_TO_GAME_TABLE'
export const SELECT_CARD = 'SELECT_CARD'
export const CLEAR_SELECTED_CARD = 'CLEAR_SELECTED_CARD'
export const ADD_CARD_TO_PLAYER_TABLE_CARDS = 'ADD_CARD_TO_PLAYER_TABLE_CARDS'
export const REMOVE_CARD_FROM_PLAYER_TABLE_STACK = 'REMOVE_CARD_FROM_PLAYER_TABLE_STACK'
export const SET_PLAYER_TABLE_CARDS_VIOLATION = 'SET_PLAYER_TABLE_CARDS_VIOLATION'
export const REMOVE_CARD_FROM_PLAYER_HAND = 'REMOVE_CARD_FROM_PLAYER_HAND'
export const ADD_CARDS_TO_MY_HAND = 'ADD_CARDS_TO_MY_HAND'

// Game session
export const SET_GAME_DATA = 'SET_GAME_DATA'
export const SETUP_GAME = 'SETUP_GAME'
export const START_GAME = 'START_GAME'
export const NEW_PLAYER = 'NEW_PLAYER'
export const SET_PLAYER_DECK = 'SET_PLAYER_DECK'
export const INIT_PLAYER_TABLE_CARDS = 'INIT_PLAYER_TABLE_CARDS'
export const SET_PLAYER_IDENTITY = 'SET_PLAYER_IDENTITY'
