// Game play
export const ADD_CARD_TO_GAME_TABLE = 'ADD_CARD_TO_GAME_TABLE'
export const SELECT_CARD = 'SELECT_CARD'
export const CLEAR_SELECTED_CARD = 'CLEAR_SELECTED_CARD'
export const ADD_CARD_TO_PLAYER_TABLE_CARDS = 'ADD_CARD_TO_PLAYER_TABLE_CARDS'
export const REMOVE_CARD_FROM_PLAYER_TABLE_STACK = 'REMOVE_CARD_FROM_PLAYER_TABLE_STACK'
export const SET_PLAYER_TABLE_CARDS_VIOLATION = 'SET_PLAYER_TABLE_CARDS_VIOLATION'
export const REMOVE_CARD_FROM_PLAYER_HAND = 'REMOVE_CARD_FROM_PLAYER_HAND'

// Game session
export const CREATE_GAME = 'CREATE_GAME'
export const SETUP_GAME = 'SETUP_GAME'
