const ADD_CARD_TO_GAME_TABLE = 'ADD_CARD_TO_GAME_TABLE'
const SELECT_CARD_FROM_PLAYER_HAND = 'SELECT_CARD_FROM_PLAYER_HAND'
const CLEAR_SELECTED_PLAYER_CARD = 'CLEAR_SELECTED_PLAYER_CARD'

export {
	ADD_CARD_TO_GAME_TABLE,
	SELECT_CARD_FROM_PLAYER_HAND,
	CLEAR_SELECTED_PLAYER_CARD,
}