const ADD_CARD_TO_GAME_TABLE = 'ADD_CARD_TO_GAME_TABLE'
const SELECT_CARD = 'SELECT_CARD'
const CLEAR_SELECTED_CARD = 'CLEAR_SELECTED_CARD'

export {
	ADD_CARD_TO_GAME_TABLE,
	SELECT_CARD,
	CLEAR_SELECTED_CARD,
}